apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: default
spec:
  selector:
    app: elasticsearch-master
  type: NodePort
  ports:
    - name: http
      port: 9200
      targetPort: 9200
      nodePort: 32000  

