# Data 節點配置文件
# 專門用於資料儲存和查詢的節點

---
# 叢集配置
clusterName: "twcc-cluster"
nodeGroup: "data"

# 連接到 Master 服務
masterService: "twcc-cluster-master"

# 節點角色配置 - 純 Data 節點
roles:
  - data
  - data_content
  - data_hot
  - data_warm

# Data 節點數量 (基於您的 elk_worker 群組)
replicas: 1
minimumMasterNodes: 1

# Elasticsearch 版本
esMajorVersion: "8"

# 叢集配置
esConfig:
  elasticsearch.yml: |
    cluster.name: "twcc-cluster"
    discovery.seed_hosts:
      - "twcc-cluster-master-headless"
    node.name: "${HOSTNAME}"
    network.host: 0.0.0.0
    http.port: 9200
    transport.port: 9300
    
    # Data 節點特化設定 (roles 已定義，這些可以移除)
    # node.data: true
    # node.master: false
    # node.ingest: false
    
    # 效能調整
    bootstrap.memory_lock: false
    indices.memory.index_buffer_size: 40%
    indices.queries.cache.size: 20%
    indices.fielddata.cache.size: 30%
    
    # 安全設定
    xpack.security.enabled: true
    xpack.security.transport.ssl.enabled: true
    xpack.security.transport.ssl.verification_mode: certificate
    xpack.security.transport.ssl.keystore.path: /usr/share/elasticsearch/config/certs/elastic-certificates.p12
    xpack.security.transport.ssl.truststore.path: /usr/share/elasticsearch/config/certs/elastic-certificates.p12

# 憑證設定
createCert: true

# 映像檔設定
image: "docker.elastic.co/elasticsearch/elasticsearch"
imageTag: "8.5.1"
imagePullPolicy: "IfNotPresent"

# JVM 設定 - 調整為合理配置 (heap 1.5g，總記憶體 3Gi)
esJavaOpts: "-Xmx1500m -Xms1500m"

# 密碼設定 (與 master 節點一致)
secret:
  enabled: true
  password: "elastic"

# 資源配置 - Data 節點需要更多資源
resources:
  requests:
    cpu: "1000m"
    memory: "3Gi"
  limits:
    cpu: "2000m"
    memory: "3Gi"

# 儲存配置 - Data 節點需要更多儲存空間
persistence:
  enabled: true
  size: 20Gi
  storageClass: ""
  accessModes:
    - ReadWriteOnce

# Pod 反親和性
antiAffinity: "soft"

# 節點選擇器 - 部署到 elk_worker 群組節點
nodeSelector:
  elk-role: "worker"

# 容忍度設定
tolerations: []

# Pod 註解
podAnnotations:
  cluster-role: "data"
  
# 服務配置
service:
  enabled: true
  type: ClusterIP
  httpPort: 9200
  transportPort: 9300

# 安全上下文
podSecurityContext:
  fsGroup: 1000
  runAsUser: 1000

securityContext:
  capabilities:
    drop:
      - ALL
  runAsNonRoot: true
  runAsUser: 1000

# 健康檢查
readinessProbe:
  failureThreshold: 3
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 3
  timeoutSeconds: 5

# 系統設定
sysctlVmMaxMapCount: 262144
terminationGracePeriod: 120

# 叢集健康檢查參數
clusterHealthCheckParams: "wait_for_status=green&timeout=1s"

# 入口配置
ingress:
  enabled: false

# 監控配置
monitoring:
  enabled: true
